version: "3.9"
services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - abair
      - bat
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  abair:
    restart: on-failure
    build: ./abair
    ports:
      - "8001:8001"
  bat:
    restart: on-failure
    build: ./bat
    ports:
      - "8000:8000"
  error-check:
    restart: on-failure
    build: ./error-check
    ports:
      - "8002:8002"
