version: "3.9"
services:
  abair:
    restart: on-failure
    build: ./abair
    ports:
      - 8000:8000
  bat:
    restart: on-failure
    build: ./bat
    ports:
      - 8001:8001
  error-check:
    restart: on-failure
    build: ./error-check
    ports:
      - 8002:8002
