version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - abair
      - bat
  abair:
    restart: on-failure
    build: ./abair
    ports:
      - "8001:8001"
  bat:
    restart: on-failure
    build: ./bat
    ports:
      - "8000:8000"
  error-check:
    restart: on-failure
    build: ./error-check
    ports:
      - "8002:8002"
